spring:
  application:
    name: NeuroKids
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/kombidb?createDatabaseIfNotExist=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root123}
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs